alias vim='nvim'
alias realvim='/bin/vim'
alias wheretf='fzf --preview "bat --color=always --style=numbers --line-range :500 {}" --preview-window=up:30% --bind "ctrl-a:select-all+accept" --bind "ctrl-d:toggle-preview" --bind "ctrl-f:page-down" --bind "ctrl-b:page-up"'
alias wheretfedit='vim $(wheretf)'
alias lg='lazygit'
alias tmuxa='tmux attach || tmux new-session -s default'
alias cd='z'
alias bat='batcat'
alias ls='exa --icons --color=always --group-directories-first'
alias v="nvim"
alias ll='exa -alF --icons --color=always --group-directories-first'
alias la='exa -a --icons --color=always --group-directories-first'
alias l='exa -lF --icons --color=always --group-directories-first'
alias lf='yazi'
